spring:
  application:
    name: Spring_Security_Demo
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: "QwRHKEGqB99122FG1QxpQkHaeZRIK0+Qi2TpUE/l3Lo="
  expiration: 3600000  # 1 hour in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    com.example.securitydemo: INFO